"""
Nexom server settings.

This file is generated by Nexom buildTools.
"""
# ======== module ========
APP_DIR: str = "__pwd_dir__"
TEMPLATES_DIR: str = "__pwd_dir__/templates"

# ======== gunicorn ========
ADDRESS: str = "__g_address__"
PORT: int = __g_port__
WORKERS: int = __g_workers__
RELOAD: bool = __g_reload__